# Общие настройки
#
# Текущее окружение
# Влияет на формат и уровень логирования.
# Возможные варианты:
# local - текстовый формат с уровнем debug
# dev - json вормат уровня bebug
# prod - json формат уровня info
env: local
# лог-файл приложения
log_file: /var/log/apiserver/server.log

# Настроки API сервера
server:
  # Адрес и порт, на котором будет запущен сервер
  bind_addr: :8080
  # Максимальная продолжительность чтения запроса, включая тело.
  # Нулевое или отрицательное значение означает отсутствие таймаута
  timeout: 5s 
  # Максимальное ожидание следующего запороса для поддержания активного соединения. 
  # Если равно нулю, но используется значение из timeout. 
  idle_timeout: 30s 

# Настроки HTTP клиента для проверки файлов на удаленных серверах
client:
  # Максимальное время ожидания ответа от удаленного сервера.
  timeout: 30s
  # Значение заголовка User-Agent для HTTP клиента
  user_agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
